### ISSUE TITLE
2d sbp data tensor parallel training bug

### ISSUE THREAD

**Issue by L1aoXingyu** [Oneflow-Inc/oneflow#7134]
## Summary

Training model with 2d sbp data&tensor parallel will raise errors when graph building.

```shell
File "/workspace/oneflow/python/oneflow/nn/graph/graph.py", line 576, in _build_graph
    oneflow._oneflow_internal.CurJobBuildAndInferCtx_Complete()
IndexError: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
```

![image](https://user-images.githubusercontent.com/19245504/147632297-abc877e7-ffab-46d9-921d-fd01fd3e0d89.png)

- 120ecadf3 -> error
- f27860650 -> ok

## Code to reproduce bug

Use this repo and branch https://github.com/Oneflow-Inc/libai/tree/dev_lxy_bert_profile can reproduce the errors.

## System Information

```
version: 0.6.0+cu111.git.f27860650
git_commit: 120ecadf3
cmake_build_type: Release
rdma: False
mlir: False
```

**Comment by strint** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/7032

引入了一个bug，辛苦 @jackalcooper 看下

**Comment by jackalcooper** [comment]
> ## Code to reproduce bug
> Use this repo and branch https://github.com/Oneflow-Inc/libai/tree/dev_lxy_bert_profile can reproduce the errors.

- Could you provide a minimum python script to reproduce the bug?
- Or use gdb to run and get the stacktrace

**Comment by leaves-zwx** [comment]
I have found the reason for this bug located at https://github.com/Oneflow-Inc/oneflow/blob/89547d047c600e800a804e2b4ecfed3955df362e/oneflow/core/operator/operator.cpp#L758 and introduced by https://github.com/Oneflow-Inc/oneflow/pull/7077.

The reason is that he number of dimensions of nd_sbp is 1 and the number of dimensions of parallel_hierarchy is 2.

I'll submit a pull request to fix this problem.
