### ISSUE TITLE
question about cuda permute

### ISSUE THREAD

**Issue by leiwen83** [Oneflow-Inc/oneflow#8457]
I check the oneflow source code, and find using oneflow to permute the tensor, it seems don't call the op in oneflow/core/ep/cuda/primitive/permute.cu? Currently I haven't other place implement the cuda permute, so my question is how oneflow handle the permute in cuda case?

```
import oneflow as flow

x=flow.randn(2,3).cuda()
y=x.permute(1,0)
```

**Comment by wyg1997** [comment]
It actually has not executed permute kernel here, because tensor_x and tensor_y share same memory and use different stride. You can print their stride with `print(x.stride(), y.stride())`.

We have an environment variable named `ONEFLOW_DISABLE_VIEW=True/False` to control whether enable memory shared for some operators (e.g. view, transpose, permute, ...). You can find related code at https://github.com/Oneflow-Inc/oneflow/blob/3cbf3927792bdd5dc6c1907904ed58823631aeec/oneflow/core/functional/impl/math_functor.cpp#L885-L885

**Comment by leiwen83** [comment]
I see...
Very interesting feature. After disable view, now it could call into the real permute kernel.

Thx.
